In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [3]:
df = pd.read_csv('marks.csv')
df

Maths  CS  Result
0       4   3       0
1       6   7       1
2       7   8       1
3       5   5       0
4       8   8       1
5       4   3       0
6       2   1       0
7       6   9       1
8       4   3       0
9       9   9       1
10      7   9       1
11      3   2       0
12      6   6       1
13      8   9       1

In [4]:
X = df.drop('Result', axis = 1)
y = df.Result

In [5]:
# p=2, metric='minkowski' = Euclidean
# p=1, metric='minkowski' = Manhattan
knn = KNeighborsClassifier(n_neighbors=5, p=2, metric='minkowski')
knn.fit(X, y)
y_pred = knn.predict(X)
y_pred

array([0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1])

In [6]:
df['Pred'] = y_pred
df

Maths  CS  Result  Pred
0       4   3       0     0
1       6   7       1     1
2       7   8       1     1
3       5   5       0     0
4       8   8       1     1
5       4   3       0     0
6       2   1       0     0
7       6   9       1     1
8       4   3       0     0
9       9   9       1     1
10      7   9       1     1
11      3   2       0     0
12      6   6       1     1
13      8   9       1     1

In [7]:
accuracy_score(y , y_pred)

1.0

In [8]:
confusion_matrix(y, y_pred)

array([[6, 0],
       [0, 8]])

In [9]:
m = int(input('Enter maths marks:'))
c = int(input('Enter cs marks:'))
knn.predict([[m , c]])

Enter maths marks: 5
Enter cs marks: 5


array([0])